apiVersion: v1
kind: Pod
metadata:
  name: invalid-app
spec:
  initContainers:
  - image: alpine
    name: third
  containers:
  - image: quay.io/jetstack/cert-manager-controller:v1.0.4
    name: first
  - image: openjdk:11.0.9.1-jre
    name: second
  #ephemeralContainers:
  #- image: c3dummy/invalid-image
  #  name: third
